hoverboard_driver_node:
  ros__parameters:
    acc: 2.0
    dec: 2.0
    x_kp: 50.0
    x_ki: 12.0
    x_kd: 2.0
    x_kff: 50.0
    x_d_alpha: 0.1
    x_o_alpha: 1.0
    w_kp: 200.0
    w_ki: 18.0
    w_kd: 1.0
    w_kff: 40.0
    w_d_alpha: 0.1
    w_o_alpha: 1.0
        