joy_node:
  ros__parameters:
    dev: "/dev/input/js0"
    deadzone: 0.3
    autorepeat_rate: 0.0
    # autorepeat_rate: 150.0
    # Set to 0 or delete line for fail-safe !
    # Do not repeat the last command received
    # When disconnection occurs, Do not publish old commands.
